services:
  - type: web
    plan: starter
    name: council-scraper-web
    region: frankfurt
    runtime: ruby
    buildCommand: "WEB=1 ./bin/render-build.sh"
    startCommand: "WEB=1 bundle exec puma -C config/puma.rb"
    envVars:
      - fromGroup: prod-settings
      - key: REDIS_URL
        fromService:
          type: redis
          name: council-scraper-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
  - type: worker
    plan: starter
    name: council-scraper-sidekiq
    region: frankfurt
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec sidekiq -C config/sidekiq.yml"
    envVars:
      - fromGroup: prod-settings
      - key: REDIS_URL
        fromService:
          type: redis
          name: council-scraper-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
  - type: redis
    name: council-scraper-redis
    ipAllowList: []
    region: frankfurt # optional (defaults to oregon)
    plan: starter # optional (defaults to starter)
    maxmemoryPolicy: volatile-lru # optional (defaults to allkeys-lru)
envVarGroups:
  - name: prod-settings
    envVars:
      - key: AWS_OPENSEARCH_PREFIX
        value: prod
      - key: AWS_OPENSEARCH_REGION
        value: eu-central-1
      - key: AWS_OPENSEARCH_ACCESS_KEY_ID
        sync: false
      - key: AWS_OPENSEARCH_SECRET_KEY
        sync: false
      - key: AWS_OPENSEARCH_HOST
        value: https://search-council-gateway-7d7lf7sktdklkart3q2zn4325i.eu-central-1.es.amazonaws.com
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_ACCESS_TOKEN
        sync: false
      - key: OPENAI_MODEL
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
